dist: trusty
addons:
  chrome: stable
jdk:
  - oraclejdk8
language: groovy
sudo: required
cache:
  directories:
  - "$HOME/.gradle/caches"
  - "$HOME/.gradle/wrapper"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
install: true
